// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0oiG0C4JdJ4XoaFSRiFRvoY_O06c4O6Q',
    appId: '1:368296205666:web:6311852c5c5f28f877603b',
    messagingSenderId: '368296205666',
    projectId: 'assignup-74175',
    authDomain: 'assignup-74175.firebaseapp.com',
    storageBucket: 'assignup-74175.firebasestorage.app',
    measurementId: 'G-CRE5DX30NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArY7YqTaSNVL5x8yklWHvpIXj1eVRpo40',
    appId: '1:368296205666:android:c030d55293c1474f77603b',
    messagingSenderId: '368296205666',
    projectId: 'assignup-74175',
    storageBucket: 'assignup-74175.firebasestorage.app',
  );
}
